name: Update BTC Price Data Daily

on:
  schedule:
    - cron: '5 * * * *'
  workflow_dispatch:

jobs:
  update-csv:
    runs-on: ubuntu-latest
    permissions:
      contents: write # This line is crucial to allow the action to push changes

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script to update data
        run: python coinmarket_api.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add btc-usd-max.csv
          # Only commit if there are changes to the file
          git diff --quiet && git diff --staged --quiet || git commit -m "Automated BTC data update"
          git push
